spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/course_management_final?stringtype=unspecified
    username: postgres
    password: 0363635725tT@
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: false

server:
  port: 8081

app:
  jwt:
    secret: super-secret-key-change-this-in-production-must-be-256-bits-long
    expiration-ms: 86400000